# Conda environment for lbx_robotics
name: lbx_robotics_env
channels:
  - conda-forge # Prioritize conda-forge for broader package availability
  - defaults
  # - intel            # Commenting out Intel channel due to access issues
dependencies:
  # --- Python Version ---
  - python=3.10 # Align with ROS Humble

  # --- Build Tools ---
  - compilers # C, C++, Fortran compilers
  - cmake # Cross-platform build system generator
  - pkg-config # Helper tool for finding installed libraries

  # --- C++ Libraries for libfranka ---
  # Note: System packages like Poco, Eigen3, and Boost are installed via apt
  # in the setup_environment.sh script to ensure compatibility with ROS2
  - eigen # Linear algebra library (conda version for Python bindings)
  - pinocchio # For libfranka dynamics computations

  # --- Core Processing & Numerics ---
  - numpy
  - scipy
  - opencv
  - pyyaml

  # --- Communication & Networking ---
  - protobuf=3.20.3 # Pin to a version compatible with ROS2 Humble & Gazebo
  - libprotobuf=3.20.3 # Corresponding C++ library
  - websocket-client
  - websockets
  - requests
  - pyzmq
  - psutil

  # --- Vision & Sensors ---
  # Explicitly try from conda-forge
  - conda-forge::librealsense
  - conda-forge::pyrealsense2

  # --- Data Recording & Visualization ---
  - mcap
  - blosc
  # - foxglove-websocket # To be installed via pip

  # --- Development & Code Quality ---
  - black
  - flake8

  # --- ROS2 Humble specific ---
  - empy=3.3.4 # For ROS2 message generation

  # --- Pip for packages not on conda or for specific versions ---
  - pip
  # Pip can be used for packages listed in requirements.txt after env creation
  # e.g., using a pip section here or a separate requirements.txt file:
  # - pip:
  #   - some-pip-only-package
  #   - -r requirements.txt # If you want to install pip requirements during env creation
