# Conda environment for lbx_robotics
name: lbx_robotics_env
channels:
  - conda-forge # Prioritize conda-forge for broader package availability
  - defaults
  # - intel            # Commenting out Intel channel due to access issues
dependencies:
  # --- Python Version ---
  - python=3.10 # Align with ROS Humble

  # --- Core Processing & Numerics ---
  - numpy
  - scipy
  - opencv
  - pyyaml

  # --- Communication & Networking ---
  - protobuf
  - websocket-client
  - websockets
  - requests
  - pyzmq
  - psutil

  # --- Vision & Sensors ---
  # Explicitly try from conda-forge
  - conda-forge::librealsense
  - conda-forge::pyrealsense2

  # --- Data Recording & Visualization ---
  - mcap
  - blosc
  - foxglove-websocket

  # --- Development & Code Quality ---
  - black
  - flake8

  # --- Pip for packages not on conda or for specific versions ---
  - pip
  # Pip can be used for packages listed in requirements.txt after env creation
  # e.g., using a pip section here or a separate requirements.txt file:
  # - pip:
  #   - some-pip-only-package
