global_settings:
  enable_sync: false
  align_depth_to_color: true
  test_settings:
    test_duration_sec: 2.0
    min_depth_coverage_pct: 30.0
cameras:
  realsense_218622272999:
    enabled: true
    type: realsense
    serial_number: '218622272999'
    device_id: realsense_218622272999
    color:
      width: 640
      height: 480
      fps: 30
      format: bgr8
    depth:
      enabled: true
      width: 640
      height: 480
      fps: 30
    transforms:
      parent_frame: base_link
      camera_frame: realsense_218622272999_link
      optical_frame: realsense_218622272999_optical_frame
      translation:
      - 0.1
      - 0.0
      - 0.5
      rotation_deg:
      - 0
      - 0
      - 0
    description: Intel RealSense D405
