# Franka FR3 Configuration for LBX Robotics
# Contains all robot-specific parameters for the Franka FR3 arm and MoveIt.

franka_fr3:
  # ----- Robot Connection -----
  robot_ip: "192.168.1.60" # Default IP, can be overridden by run.sh or launch args
  use_fake_hardware: false # Set to true for simulation/testing without a real robot

  # ----- MoveIt Configuration -----
  planning_group: "fr3_arm" # Main planning group for the arm
  gripper_planning_group: "fr3_hand" # Planning group for the gripper
  end_effector_link: "fr3_hand_tcp" # Default end-effector link
  planning_frame: "base" # Base frame for planning (e.g., fr3_link0 or world)
  load_gripper: true # Whether to load the gripper model and controllers

  # ----- Controller Settings -----
  # Names of controllers to be loaded by MoveIt / ros2_control
  # These typically match those in franka_fr3_moveit_config/config/controllers.yaml
  # or your custom controller configurations.
  arm_controller_name: "fr3_arm_controller"
  gripper_controller_name: "franka_gripper_controller" # Example, adjust if different

  # ----- RViz Settings -----
  enable_rviz: true # Whether to launch RViz by default
  # rviz_config_file: "package://lbx_franka_moveit/rviz/moveit.rviz" # Path to RViz config (example)

  # ----- Safety & Limits -----
  # These are typically set in MoveIt config files (e.g., joint_limits.yaml)
  # but can be referenced or overridden if necessary.
  default_velocity_scaling: 0.3
  default_acceleration_scaling: 0.3

  # ----- Other Parameters -----
  description_package: "lbx_franka_description" # Package containing URDF
  moveit_config_package: "lbx_franka_moveit" # Package containing MoveIt config
  # log_level: "INFO" # Default log level for nodes (DEBUG, INFO, WARN, ERROR)
