# Controller configuration for Franka FR3
controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz - FR3 supports 1kHz control

fr3_arm_controller:
  type: joint_trajectory_controller/JointTrajectoryController
  joints:
    - fr3_joint1
    - fr3_joint2
    - fr3_joint3
    - fr3_joint4
    - fr3_joint5
    - fr3_joint6
    - fr3_joint7
  command_interfaces:
    - position
    - velocity
  state_interfaces:
    - position
    - velocity
    - effort
  state_publish_rate: 100.0
  action_monitor_rate: 20.0
  allow_partial_joints_goal: false
  constraints:
    stopped_velocity_tolerance: 0.01
    goal_time: 0.0

  # FR3-specific gains
  gains:
    fr3_joint1: { p: 600.0, i: 0.0, d: 30.0 }
    fr3_joint2: { p: 600.0, i: 0.0, d: 30.0 }
    fr3_joint3: { p: 600.0, i: 0.0, d: 30.0 }
    fr3_joint4: { p: 600.0, i: 0.0, d: 30.0 }
    fr3_joint5: { p: 250.0, i: 0.0, d: 10.0 } # Lower gains for wrist
    fr3_joint6: { p: 250.0, i: 0.0, d: 10.0 }
    fr3_joint7: { p: 250.0, i: 0.0, d: 10.0 }

fr3_hand_controller:
  type: position_controllers/GripperActionController
  joint: fr3_finger_joint1
  action_monitor_rate: 20.0
  goal_tolerance: 0.001 # 1mm precision
  max_effort: 70.0 # FR3 gripper max force
  allow_stall: true
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0

# Alternative: Direct position controller for low-latency teleoperation
fr3_position_controller:
  type: forward_command_controller/ForwardCommandController
  joints:
    - fr3_joint1
    - fr3_joint2
    - fr3_joint3
    - fr3_joint4
    - fr3_joint5
    - fr3_joint6
    - fr3_joint7
  interface_name: position
