# Kinematics configuration for Franka FR3
fr3_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3

  # FR3-specific parameters
  position_only_ik: false

  # Joint weights for IK solver (prioritize wrist joints for orientation)
  joint_weights: [1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0]
