cam_info:
  -
    cam_id: 1
    cam_serial_num: "147322072736"
    type: realsense
  -
    cam_id: 2
    cam_serial_num: "028522071213"
    type: realsense
  # -
  #   cam_id: 3
  #   cam_serial_num: "147322072546"
  #   type: realsense
  # -
  #   cam_id: 4
  #   cam_serial_num: "152222073516"
  #   type: realsense
  # -
  #   cam_id: 51
  #   cam_serial_num: 2 #24
  #   type: fisheye

cam_config:
  realsense:
    width: 640 #1280
    height: 480 #720
    fps: 30
    processing_preset: 1
    depth: True #False
  fisheye:
    width: 640
    height: 480
    fps: 30
