defaults:
  - _self_
  - camera

storage_path: "/home/siddhant/github/Franka-Teach/data/extracted_data/0116_human_bread_on_plate"
demo_num: 0
collect_img: True
collect_depth: False
collect_state: True
collect_reskin: False
