defaults:
  - _self_
  - camera

storage_path: "/home/siddhant/github/Franka-Teach/data/extracted_data/0218_put_bowl_with_bread_in_oven_and_close"
demo_num: 0
collect_img: True
collect_depth: False
collect_state: True
collect_reskin: False
