# Intel RealSense Camera Configuration for lbx_robotics
# ROS2-compatible configuration for Intel RealSense cameras

global_settings:
  enable_sync: false
  align_depth_to_color: true
  test_settings:
    test_duration_sec: 3.0
    min_depth_coverage_pct: 20.0
  performance_settings:
    enable_auto_exposure: true
    auto_exposure_priority: false
    depth_processing_preset: 1
    decimation_filter: 2
    spatial_filter: true
    temporal_filter: true

cameras:
  realsense_218622277093:
    enabled: true
    type: realsense
    serial_number: '218622277093'
    device_id: realsense_218622277093
    color:
      width: 640
      height: 480
      fps: 15
      format: bgr8
    depth:
      enabled: true
      width: 640
      height: 480
      fps: 15
    topics:
      base: "/cameras/overhead_camera"
    transforms:
      parent_frame: base_link
      camera_frame: realsense_218622277093_link
      optical_frame: realsense_218622277093_optical_frame
      translation:
        - 0.1
        - 0.0
        - 0.5
      rotation_deg:
        - 0
        - 0
        - 0
    description: Intel RealSense D405
    
  realsense_218622272999:
    enabled: true
    type: realsense
    serial_number: '218622272999'
    device_id: realsense_218622272999
    color:
      width: 640
      height: 480
      fps: 15
      format: bgr8
    depth:
      enabled: true
      width: 640
      height: 480
      fps: 15
    topics:
      base: "/cameras/wrist_camera"
    transforms:
      parent_frame: base_link
      camera_frame: realsense_218622272999_link
      optical_frame: realsense_218622272999_optical_frame
      translation:
        - 0.1
        - 0.0
        - 0.5
      rotation_deg:
        - 0
        - 0
        - 0
    description: Intel RealSense D405
