version: '3.8'

services:
  # Base service for common configuration
  ros2_moveit_franka_base: &base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    image: ros2_moveit_franka:latest
    container_name: ros2_moveit_franka
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - ROBOT_IP=192.168.1.59
    volumes:
      # X11 forwarding for GUI applications
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Mount the current directory for development
      - .:/home/ros/ros2_moveit_franka_dev:rw
    stdin_open: true
    tty: true
    working_dir: /home/ros
    user: ros

  # Service for running with real robot
  real_robot:
    <<: *base
    container_name: ros2_moveit_franka_real
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - ROBOT_IP=192.168.1.59
      - USE_FAKE_HARDWARE=false
    command: >
      bash -c "
        echo '🤖 Starting MoveIt with REAL robot at ${ROBOT_IP:-192.168.1.59}' &&
        echo '⚠️  Make sure robot is connected and in programming mode!' &&
        echo 'Press Ctrl+C to stop' &&
        echo '' &&
        ./launch_moveit.sh
      "

  # Service for simulation (fake hardware)
  simulation:
    <<: *base
    container_name: ros2_moveit_franka_sim
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - ROBOT_IP=192.168.1.59
      - USE_FAKE_HARDWARE=true
    command: >
      bash -c "
        echo '🔧 Starting MoveIt with SIMULATION (fake hardware)' &&
        echo '✅ Safe for testing without real robot' &&
        echo 'Press Ctrl+C to stop' &&
        echo '' &&
        ./launch_moveit.sh
      "

  # Service for running the demo
  demo:
    <<: *base
    container_name: ros2_moveit_franka_demo
    depends_on:
      - real_robot
    command: >
      bash -c "
        echo '🎯 Starting Franka FR3 Demo...' &&
        echo 'Waiting for MoveIt to be ready...' &&
        sleep 10 &&
        ./run_demo.sh
      "

  # Interactive development container
  dev:
    <<: *base
    container_name: ros2_moveit_franka_dev
    volumes:
      # Additional development volumes
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/home/ros/ros2_moveit_franka_dev:rw
      - ~/.gitconfig:/home/ros/.gitconfig:ro
      - ~/.ssh:/home/ros/.ssh:ro
    command: bash

# Networks
networks:
  default:
    driver: bridge
