version: "3.8"

services:
  ros2_moveit_franka:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    image: ros2_moveit_franka:latest
    container_name: ros2_moveit_franka_dev

    # Environment variables
    environment:
      - ROS_DOMAIN_ID=42
      - ROBOT_IP=192.168.1.59
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    # Network configuration
    network_mode: host

    # Volume mounts for development
    volumes:
      # Mount the package source for development
      - .:/workspace/ros2_ws/src/ros2_moveit_franka:rw
      # X11 forwarding for GUI applications (RViz)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Share host's .bashrc_additions if it exists
      - ${HOME}/.bashrc_additions:/root/.bashrc_additions:ro
      # Persistent bash history
      - ros2_moveit_franka_bash_history:/root/.bash_history

    # Device access for real robot communication
    devices:
      - /dev/dri:/dev/dri # GPU access for visualization

    # Capabilities for real-time communication
    cap_add:
      - SYS_NICE # For real-time scheduling
      - NET_ADMIN # For network configuration

    # Interactive terminal
    stdin_open: true
    tty: true

    # Working directory
    working_dir: /workspace/ros2_ws

    # Health check
    healthcheck:
      test: ["CMD", "ros2", "node", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Simulation service (for testing without real robot)
  ros2_moveit_franka_sim:
    extends: ros2_moveit_franka
    container_name: ros2_moveit_franka_sim
    environment:
      - ROS_DOMAIN_ID=43
      - USE_FAKE_HARDWARE=true
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1

    # Override command to start in simulation mode
    command: >
      bash -c "
        echo 'Starting ROS 2 MoveIt Franka in simulation mode...' &&
        ros2 launch ros2_moveit_franka franka_demo.launch.py use_fake_hardware:=true
      "

volumes:
  ros2_moveit_franka_bash_history:
    driver: local
